---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-persistentvolumeclaim
  namespace: collectors-channel
  annotations:
    nfs.io/storage-path: grafana
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
