---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-persistentvolumeclaim
  namespace: collectors-channel
  annotations:
    nfs.io/storage-path: influxdb
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
