---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: collectors-channel
spec:
  selector:
    app: influxdb-deployment
  ports:
    - name: http-port
      targetPort: http-port
      protocol: TCP
      port: 8086
