apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: collectors-channel
spec:
  encryptedData:
    database: AgBLVmRjXmVQye3O+1yYYdkdZgZimWag/+OMJHlfLZur9p9STMZ14JIYTdyDS+hgL1CGXGvHlt5zvpg5xxdITsRUdz68K+jZ4R7+Kpw5uK5ZYrAc0VXoGOBmh1HFEjhS8BxVSA6Tz9tO/nP5+8k+UgpYiXpdeEsl4tjeoot52ktIy5Ci1lkTxdhKfwAhXI4yuqNm1lzcggijjTf2mg0Q+PIMmOVQvmBWbhuwiKORlgebf5F5k7vacrcO5fyzFagjefsgFxhh3pVVSiUdjSo9ZKJatW9CH0933UY6eUIcXRpx9tjyF7+1bWQzSSPStfeJGqO/lnrD72WtizbyzmsTdeElPfPCCQqR2Fg0yhyVZGKKUIlmKHa6AE2yIaBFgf5QMFzb7sk7+cJdfMxapORfE1jxgKo25d27+dOQBsbUtWUaEl5MXUUTZ4b+AM7v1u1XxtjxCcGZ43JcNRY9i0OMnLD++JHBizNU2JXLrFYIpNeezBbriz4sgCPcIE3nAPL5jLQRKMcMcfUzVZ/bAzD0Iom02J28p2uCbMv0pIec6N1eWBKFtUNaMyPLA8mNACYZEULgXNu0VqJ9fdxJy8aftowXkUCx+plHShUTohXdUfQtQdIi6nzHYMkcmixeGfRbee8We9L7XtnZK7CH49l252L4jgTpCHuxpmEk3OyYvEQZmCOOQYALFBLSMHSEy1gJEyUwscJ4qKg=
    username: AgCwDbUda0Lo3/oHn2FcGLMAPACQj/7ZecXFh8aAsvbweZOHW/MuYKdBqkUHEsfNy99k62qLING/1/pMT+VpjNZm0q/55JcCJPr9CVRVAZtJ5r6FFHXhk2Hq1qoGPLRukZF5izQDzcENeHzOD8U215pwsQlsAN6Hb3f3FWGR/DiwWn1dwnfYGJNDnimMSOQEPk4h/O9T3NrcDdls2DHECYpMIbdLeu+XYkOsPhlxXeP00igAWErkbbjPPRmmgESXfVmf0DfVNMiY2ZrD4vnYysE2wFcLdDGoZ7mq+cFFE2AKsAsfQgtBBxkHkdh+KlGnhxJ/lZScgaTH/EQ57kIeonBRdt5RX1DzohX8NO7xyfjArClx9w46JxYQlZ+q/QijTPRp0fSnWEGcOHKOMrYYtFaPMvr6F4ZWWKQfVWYs5QWEmMcazk2lz14OYMtec0HuZXzU7bW8wuGNTvYjKmhMp2ll9SMn9bWbSWZCtT0NqlkBB0EXaxUCj3haLPPJ/Nb38fI1Dl7WqQnbrr7mw2z2IVlc6qwcrnvJ35PiRsrKkGimeIDQ1OAX1oN88CWg801axMAcyo/bww0S1bB4j+tVMD0ItpQVj04+zBlrtGRNmrpyokcVJyJYZe51RnFZBSmLKsO4dInv751qaLvelD5rzMVEV6Q/4UTC/4rUXpg9Sw3wG6ihE1hu4QbT8n6/6DwRGx5lWc2dr+q4wjPw
  template:
    metadata:
      annotations:
        secret-generator.v1.mittwald.de/autogenerate: password
      creationTimestamp: null
      name: mongo-secret
      namespace: collectors-channel
