---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: collectors-channel
spec:
  selector:
    app: mongo-deployment
  ports:
    - name: http-port
      targetPort: http-port
      protocol: TCP
      port: 27017
