---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: collectors-channel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
        version: "1.3.0"
    spec:
      containers:
        - name: collectors-channel-api
          image: paulosalgado/collectors-channel-api:1.3.0
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 5000
          env:
            - name: TZ
              value: America/Sao_Paulo
            - name: AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: username
            - name: AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: password
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: mongoUrl
