apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secret
  namespace: collectors-channel
spec:
  encryptedData:
    username: AgDXEwTPfxjiz3uXvNI22jTiAgRxcAFpgltH7/VsOJkOjTG0o6nCVmd1lqHs549VlQV1sPo+ScHPhMVjj1mHng5asgrwMSGl2XuqOji4jzfLwL8OFtsbQ9qX1X8yjTvUyxJpFFEM66oh0IoTrszfJJ/Hjvly7IBYxQQCtC1Fmab6Gsrcur0d8Sz7qsRYbQqothyqLqzb86oEVYAQDWHsEoJw9ylXgJhmGSVk6ZHsIGPuBTiH8/4PM2khQGjhGDnayF1m4dGyHDonx+2MGWZ1x9KuTmVuxjj69Cy0xpaSNGNAHSoZ+Dppf91kfaTocn7+Gf5eIPr2W/F9f1zjFTrdhYVPYiZXvGRje5/7/pJWHOZng6bhM1oHJ3nslEH6Y1zRYEnnIpGLMfsi6U4BdQZGDl6yY6CkG5M5cMYu08HdvUjpBl4IJ5p3eH+bGCi31wCkn21Occ8y5VcUx55v2EtyL77m+FLokobD3oqAo8KvMvLoMqrw6FMkG//vLaYeLFT0b5FA7qcQfwordyqQ5zE81JaPbAUc3AqmAWTd+fM1XAmhO5IjoGBiXXVDw+K3LDaM34a4UYpQC3wVyyvajbMUWAbyDwlI49v+AJtLN9wyBnxZh1yBoqVpASKYtjYbQkcNWmhDih+3XKI/ErHR72yIhGfwyy8P2NgV8mKD6ooddMG+2xB1KTht9t+myMbYnd5XXZIookdgU0aolPYw
  template:
    metadata:
      annotations:
        secret-generator.v1.mittwald.de/autogenerate: password
      creationTimestamp: null
      name: api-secret
      namespace: collectors-channel
